# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TSP_BB
                                 A QGIS plugin
 Get the best route
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-08
        copyright            : (C) 2019 by Lingyu LI
        email                : 2587326506@qq.cm
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TSP_BB class from file TSP_BB.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TSP_BB import TSP_BB
    return TSP_BB(iface)
